global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'nodes'
    scrape_interval: 1m
    scrape_timeout: 10s
    static_configs:
     - targets: ['localhost:9100']

  - job_name: 'iot_th'
    scrape_interval: 1m
    scrape_timeout: 10s
    static_configs:
     - targets: ['localhost:8000']